#!/bin/bash

read -p "Enter the domain name: (something like domain1.com)\n" -e DOMAIN
mkdir -p $HOME/public_html/$DOMAIN/{public,private,log,cgi-bin,backup}

echo "<html>
  <head>
    <title>$DOMAIN</title>
  </head>
  <body>
    <h1>$DOMAIN</h1>
  </body>
</html>
" > public_html/$DOMAIN/public/index.html

sudo chmod -R a+rX $HOME/public_html
sudo chmod a+rx $HOME

echo "# Place any notes or comments you have here
# It will make any customization easier to understand in the weeks to come

# domain: $DOMAIN
# public: $HOME/public_html/$DOMAIN/

<VirtualHost *:80>

  # Admin email, Server Name (domain name) and any aliases
  ServerAdmin webmaster@$DOMAIN
  ServerName  www.$DOMAIN
  ServerAlias $DOMAIN


  # Index file and Document Root (where the public files are located)
  DirectoryIndex index.html
  DocumentRoot $HOME/public_html/$DOMAIN/public


  # Custom log file locations
  LogLevel warn
  ErrorLog  $HOME/public_html/$DOMAIN/log/error.log
  CustomLog $HOME/public_html/$DOMAIN/log/access.log combined

  ScriptAlias /cgi-bin/ $HOME/public_html/$DOMAIN/cgi-bin/
  <Location /cgi-bin>
  Options +ExecCGI
  </Location>

  <Directory $HOME/public_html/$DOMAIN/public>
  Options -Indexes
  Options -Includes
  Options +SymLinksIfOwnerMatch
  #Options -FollowSymLinks
  AllowOverride All
  </Directory>

</VirtualHost>
" > /etc/apache2/sites-available/$DOMAIN

sudo /usr/sbin/a2ensite $DOMAIN
sudo /etc/init.d/apache2 reload

